name: run-main

on:
    push:
        branches: [master]
    pull_request:
        branches: [master]
permissions:
  contents: read
concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true
jobs:
  ci:
    name: ci
    uses: craftcms/.github/.github/workflows/ci.yml@v3
    with:
      php_version: '["8.4", "8.3", "8.2"]'
      craft_version: '5'
      node_version: '20'
      jobs: '["ecs", "phpstan"]'